version: '3.8'

services:
  app:
    image: minha-imagem:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 10s
    environment:
      - NODE_ENV=production
      - SESSION_SECRET=${SESSION_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - INTERNAL_LAWS_API_URL=${INTERNAL_LAWS_API_URL}
      - INTERNAL_LAWS_API_KEY=${INTERNAL_LAWS_API_KEY}
    volumes:
      - app_data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager  # Para garantir acesso aos volumes
    ports:
      - "80:80"
      - "443:443"
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    volumes:
      - certbot_www:/var/www/certbot/:ro
      - certbot_conf:/etc/nginx/ssl/:ro
    networks:
      - app_network

  certbot:
    image: certbot/certbot:latest
    deploy:
      replicas: 0  # Inicialmente 0, escale para 1 quando precisar renovar
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.role == manager
    volumes:
      - certbot_www:/var/www/certbot/:rw
      - certbot_conf:/etc/letsencrypt/:rw
    command: certonly --webroot --webroot-path=/var/www/certbot --email seu-email@exemplo.com --agree-tos --no-eff-email -d legislative-ai.airdata.com.br
    networks:
      - app_network

volumes:
  app_data:
    driver: local
  certbot_www:
    driver: local
  certbot_conf:
    driver: local

networks:
  app_network:
    driver: overlay
    attachable: true

configs:
  nginx_config:
    external: true  # Você precisa criar este config no Portainer primeiro
