version: '3.8'

services:
  app:
    image: airdatabr/legislative-ai:latest  # ← Coloque a imagem que você publicou
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=airdatanetwork"
        - "traefik.http.routers.legislativeai.rule=Host(`legislative-ai.airdata.com.br`)"
        - "traefik.http.routers.legislativeai.entrypoints=websecure"
        - "traefik.http.routers.legislativeai.tls=true"
        - "traefik.http.routers.legislativeai.tls.certresolver=le"
        - "traefik.http.services.legislativeai.loadbalancer.server.port=5000"
        # Redirect HTTP para HTTPS
        - "traefik.http.routers.legislativeai-http.rule=Host(`legislative-ai.airdata.com.br`)"
        - "traefik.http.routers.legislativeai-http.entrypoints=web"
        - "traefik.http.routers.legislativeai-http.middlewares=https-redirect"
        - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
    environment:
      - NODE_ENV=production
      - SESSION_SECRET=${SESSION_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - INTERNAL_LAWS_API_URL=${INTERNAL_LAWS_API_URL}
      - INTERNAL_LAWS_API_KEY=${INTERNAL_LAWS_API_KEY}
    volumes:
      - app_data:/app/data
    networks:
      - airdatanetwork

volumes:
  app_data:

networks:
  airdatanetwork:
    external: true
