version: '3.8'

services:
  assistente-legislativo:
    build: .
    container_name: assistente-legislativo
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - SESSION_SECRET=${SESSION_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - INTERNAL_LAWS_API_URL=${INTERNAL_LAWS_API_URL}
      - INTERNAL_LAWS_API_KEY=${INTERNAL_LAWS_API_KEY}
    volumes:
      - app_data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - app_network

volumes:
  app_data:

networks:
  app_network:
    driver: bridge