version: '3.8'

services:
  app:
    image: minha-imagem:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - SESSION_SECRET=${SESSION_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - INTERNAL_LAWS_API_URL=${INTERNAL_LAWS_API_URL}
      - INTERNAL_LAWS_API_KEY=${INTERNAL_LAWS_API_KEY}
    volumes:
      - app_data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    # container_name: assistente-legislativo-nginx  # ❌ REMOVER
    # restart: unless-stopped                       # ❌ REMOVER
    deploy:                                         # ✅ ADICIONAR
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot_www:/var/www/certbot/:ro
      - certbot_conf:/etc/nginx/ssl/:ro
    # depends_on:                                   # ❌ REMOVER (não suportado no Swarm)
    #   - assistente-legislativo
    networks:
      - app_network

  certbot:
    image: certbot/certbot:latest
    # container_name: assistente-legislativo-certbot # ❌ REMOVER
    deploy:                                          # ✅ ADICIONAR
      replicas: 1
      restart_policy:
        condition: none    # Certbot geralmente roda uma vez
    volumes:
      - certbot_www:/var/www/certbot/:rw
      - certbot_conf:/etc/letsencrypt/:rw
    networks:
      - app_network

volumes:
  app_data:
  certbot_www:
  certbot_conf:

networks:
  app_network:
    driver: overlay      # ✅ MUDAR de bridge para overlay
    attachable: true     # ✅ ADICIONAR
